# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x04\x64\x65mo\"O\n\x06Record\x12\x0b\n\x03int\x18\x01 \x01(\x03\x12\r\n\x05\x66loat\x18\x02 \x01(\x02\x12\x0b\n\x03rep\x18\x1b \x03(\x03\x12\x1c\n\x06nested\x18\x1c \x01(\x0b\x32\x0c.demo.Nested\"+\n\nCollection\x12\x1d\n\x07records\x18\x01 \x03(\x0b\x32\x0c.demo.Record\"$\n\x06Nested\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x02\x12\x0c\n\x04more\x18\x02 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECORD._serialized_start=20
  _RECORD._serialized_end=99
  _COLLECTION._serialized_start=101
  _COLLECTION._serialized_end=144
  _NESTED._serialized_start=146
  _NESTED._serialized_end=182
# @@protoc_insertion_point(module_scope)
